# -*- coding: utf-8 -*-
"""Graph_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHwavPF8NJ_Ur0H1RsyxFF8Zu0SMRqFW
"""

import argparse
import os.path as osp
from typing import Any, Dict, Optional
import math
import torch as th
import egnn_clean as eg

import torch
from torch.nn import (
    BatchNorm1d,
    Embedding,
    Linear,
    ModuleList,
    ReLU,
    Sequential,
)
import gc
import torch_geometric.transforms as T
from torch_geometric.loader import DataLoader
from torch_geometric.nn import global_add_pool
import inspect
from typing import Any, Dict, Optional

import torch.nn.functional as F
from torch import Tensor
from torch.nn import Dropout, Linear, Sequential

from torch_geometric.nn.conv import MessagePassing
from torch_geometric.nn.inits import reset
from torch_geometric.nn.resolver import (
    activation_resolver,
    normalization_resolver,
)
from torch_geometric.typing import Adj
from torch_geometric.utils import to_dense_batch

from mamba_ssm import Mamba
from torch_geometric.utils import degree, sort_edge_index
import torch_sparse



class GPSConv(torch.nn.Module):

    def __init__(
        self,
        channels: int,
        conv: Optional[MessagePassing],
        heads: int = 1,
        dropout: float = 0.0,
        attn_dropout: float = 0.0,
        act: str = 'relu',
        att_type: str = 'transformer',
        order_by_degree: bool = False,
        shuffle_ind: int = 0,
        d_state: int = 16,
        d_conv: int = 4,
        act_kwargs: Optional[Dict[str, Any]] = None,
        norm: Optional[str] = 'batch_norm',
        norm_kwargs: Optional[Dict[str, Any]] = None,
    ):
        super().__init__()

        self.channels = channels
        self.conv = conv
        self.heads = heads
        self.dropout = dropout
        self.att_type = att_type
        self.shuffle_ind = shuffle_ind
        self.order_by_degree = order_by_degree

        assert (self.order_by_degree==True and self.shuffle_ind==0) or (self.order_by_degree==False), f'order_by_degree={self.order_by_degree} and shuffle_ind={self.shuffle_ind}'
        if self.att_type == 'transformer':
            self.attn = torch.nn.MultiheadAttention(
                channels,
                heads,
                dropout=attn_dropout,
                batch_first=True,
            )
        if self.att_type == 'mamba':
            self.self_attn = Mamba(
                d_model=channels,
                d_state=d_state,
                d_conv=d_conv,
                expand=1
            )

        self.mlp = Sequential(
            Linear(channels, channels * 2),
            activation_resolver(act, **(act_kwargs or {})),
            Dropout(dropout),
            Linear(channels * 2, channels),
            Dropout(dropout),
        )

        norm_kwargs = norm_kwargs or {}
        self.norm1 = normalization_resolver(norm, channels, **norm_kwargs)
        self.norm2 = normalization_resolver(norm, channels, **norm_kwargs)
        self.norm3 = normalization_resolver(norm, channels, **norm_kwargs)

        self.norm_with_batch = False
        if self.norm1 is not None:
            signature = inspect.signature(self.norm1.forward)
            self.norm_with_batch = 'batch' in signature.parameters

    def reset_parameters(self):
        r"""Resets all learnable parameters of the module."""
        if self.conv is not None:
            self.conv.reset_parameters()
        self.attn._reset_parameters()
        reset(self.mlp)
        if self.norm1 is not None:
            self.norm1.reset_parameters()
        if self.norm2 is not None:
            self.norm2.reset_parameters()
        if self.norm3 is not None:
            self.norm3.reset_parameters()

    def forward(
        self,
        h: Tensor,
        x: Tensor,
        edge_index: Adj,
        batch: Optional[torch.Tensor] = None,
        **kwargs,
    ) -> Tensor:
        r"""Runs the forward pass of the module."""
        hs = []
        if self.conv is not None:  # Local MPNN.
            y,x = self.conv(h, x, **kwargs)
            y = F.dropout(h, p=self.dropout, training=self.training)
            y = y + h
            if self.norm1 is not None:
                if self.norm_with_batch:
                    y = self.norm1(y, batch=batch)
                else:
                    y = self.norm1(y)
            hs.append(y)
            print("shape of hs from MPNN:", h.shape)

        ### Global attention transformer-style model.
        if self.att_type == 'transformer':
            y, mask = to_dense_batch(h, batch)
            y, _ = self.attn(y, y, y, key_padding_mask=~mask, need_weights=False)
            h = h[mask]

        if self.att_type == 'mamba':

            if self.order_by_degree:
                deg = degree(edge_index[0], h.shape[0]).to(torch.long)
                order_tensor = torch.stack([batch, deg], 1).T
                _, h = sort_edge_index(order_tensor, edge_attr=x)
            if self.shuffle_ind == 0:
                y, mask = to_dense_batch(h, batch)
                y = self.self_attn(y)[mask]

            else:
                mamba_arr = []
                for _ in range(self.shuffle_ind):
                    y_ind_perm = permute_within_batch(h, batch)
                    y_i, mask = to_dense_batch(h[y_ind_perm], batch)
                    y_i = self.self_attn(y_i)[mask][y_ind_perm]
                    mamba_arr.append(y_i)
                y = sum(mamba_arr) / self.shuffle_ind
                print("Shape of h from mamba:", y.shape)

                # Averages the results from all shuffled versions to produce the final node representations.
        ###

        y = F.dropout(y, p=self.dropout, training=self.training)
        y = y + h  # Residual connection.
        if self.norm2 is not None:
            if self.norm_with_batch:
                y = self.norm2(y, batch=batch)
            else:
                y = self.norm2(y)
        hs.append(y)
        print("shape of hs from attention:", h.shape)

        out = sum(hs)  # Combine local and global outputs.
        print("Shape of out:", out.shape)

        out = out + self.mlp(out)
        if self.norm3 is not None:
            if self.norm_with_batch:
                out = self.norm3(out, batch=batch)
            else:
                out = self.norm3(out)

        return out

    def __repr__(self) -> str:
        return (f'{self.__class__.__name__}({self.channels}, '
                f'conv={self.conv}, heads={self.heads})')

class GraphModel(torch.nn.Module):
    def __init__(self, channels: int, in_node_nf: int, out_node_nf: int, in_edge_nf: int, hidden_nf: int, pe_dim: int, context_dim: int, time_embed_dim: int, num_layers: int, model_type: str, shuffle_ind: int, d_state: int, d_conv: int, order_by_degree: False):
        super().__init__()

        self.node_emb = Linear(64, channels - pe_dim - time_embed_dim - context_dim)
        self.context_emb = Linear(64, context_dim)
        self.context_dim = context_dim
        self.time_embed_dim = time_embed_dim
        self.pe_lin = Linear(20, pe_dim)    # PE_encoder = linear, DeepSet
        self.pe_norm = BatchNorm1d(20)
        self.edge_emb = Linear(4, channels-time_embed_dim)
        self.model_type = model_type
        self.shuffle_ind = shuffle_ind
        self.order_by_degree = order_by_degree
        self.convs = ModuleList()

        for _ in range(num_layers):
            nn = Sequential(
                Linear(channels, channels),
                ReLU(),
                Linear(channels, channels),
            )
            if self.model_type == 'egnn':
                conv = eg.EGNN(in_node_nf, hidden_nf, out_node_nf, in_edge_nf)

            if self.model_type == 'mamba':
                conv = GPSConv(channels, eg.EGNN(in_node_nf, hidden_nf, out_node_nf, in_edge_nf), heads=4, attn_dropout=0.5,
                               att_type='mamba',
                               shuffle_ind=self.shuffle_ind,
                               order_by_degree=self.order_by_degree,
                               d_state=d_state, d_conv=d_conv)

            if self.model_type == 'transformer':
                conv = GPSConv(channels, eg.EGNN(in_node_nf, hidden_nf, out_node_nf, in_edge_nf), heads=4, attn_dropout=0.5, att_type='transformer')
            self.convs.append(conv)

        self.mlp = Sequential(
            Linear(channels, channels // 2),
            ReLU(),
            Linear(channels // 2, channels // 4),
            ReLU(),
            Linear(channels // 4, 1),
        )

    def forward(self, h, pe, x, t, context, edges, edge_index, edge_attr, batch):

        h_pe = self.pe_norm(pe)        # positional_encoding = RWSE-20, LapPE-8, LapPE-16
        time_emb = timestep_embedding(t, self.time_embed_dim)
        context = self.context_emb(context)
        h = torch.cat((self.node_emb(h.squeeze(-1)), self.pe_lin(h_pe), time_emb.squeeze(1), context), dim=1)

        edge_attr = self.edge_emb(edge_attr.squeeze(-1))
        required_repeats = edge_attr.size(0) // time_emb.size(0)
        remainder = edge_attr.size(0) % time_emb.size(0)
        time_emb_edge = time_emb.repeat_interleave(required_repeats, dim=0)

        if remainder > 0:
          extra_time_emb = time_emb[:remainder]
        time_emb_edge = torch.cat((time_emb_edge, extra_time_emb), dim=0)

        assert time_emb_edge.size(0) == edge_attr.size(0), "Final sizes still do not match!"
        edge_attr = torch.cat((edge_attr, time_emb_edge.squeeze(1)), dim=-1)

        for conv in self.convs:
            if self.model_type == 'egnn':
                h = conv(h, x, edges=edges, edge_attr=edge_attr)
            else:
                h = conv(h,x, edge_index, batch, edges=edges, edge_attr=edge_attr)
        h = global_add_pool(h, batch)    # graph_pool = sum, mean
        return self.mlp(h)



def timestep_embedding(timesteps, dim, max_period=10000):
      """
    Create sinusoidal timestep embeddings.

    :param timesteps: a 1-D Tensor of N indices, one per batch element.
                      These may be fractional.
    :param dim: the dimension of the output.
    :param max_period: controls the minimum frequency of the embeddings.
    :return: an [N x dim] Tensor of positional embeddings.
    """
      half = dim // 2
      freqs = th.exp(
        -math.log(max_period) * th.arange(start=0, end=half, dtype=th.float32) / half
      ).to(device=timesteps.device)
      args = timesteps[:, None].float() * freqs[None]
      embedding = th.cat([th.cos(args), th.sin(args)], dim=-1)
      if dim % 2:
        embedding = th.cat([embedding, th.zeros_like(embedding[:, :1])], dim=-1)
      return embedding